# cloudbuild.yaml
options:
  logging: CLOUD_LOGGING_ONLY  # Send logs to Cloud Logging
  machineType: "E2_HIGHCPU_8" # Optional, adjust if needed

substitutions:
  _PROJECT_ID: $PROJECT_ID
  _REGION: "us-central1"           # Change to your Cloud Run region
  _SERVICE_NAME: "my-cloudrun-app" # Change to your service name
  _IMAGE_NAME: "my-cloudrun-app"   # Name for container image

steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}:${SHORT_SHA}',
      '.'
    ]

  # Step 2: Push Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}:${SHORT_SHA}'
    ]

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', '${_SERVICE_NAME}',
      '--image', 'gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}:${SHORT_SHA}',
      '--region', '${_REGION}',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

images:
  - 'gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}:${SHORT_SHA}'

# Optionally, you can add timeout if build may take longer
timeout: '1200s'
