# cloudbuild-deploy.yaml
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"

substitutions:
  _PROJECT_ID: $PROJECT_ID
  _REGION: "us-central1"
  _SERVICE_NAME: "my-cloudrun-app"
  _IMAGE_TAG: "latest"   # Replace with COMMIT_SHA or any tag
  _ENV: "dev"            # dev, test, prod

steps:
  # Step 1: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy $_SERVICE_NAME-$_ENV \
          --image gcr.io/$_PROJECT_ID/$_SERVICE_NAME:$_IMAGE_TAG \
          --region $_REGION \
          --platform managed \
          --quiet

  # Step 2: Make service public (optional)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run services add-iam-policy-binding $_SERVICE_NAME-$_ENV \
          --region $_REGION \
          --member=allUsers \
          --role=roles/run.invoker

    # Print service URL
      SERVICE_URL=$(gcloud run services describe my-cloudrun-app-dev \
        --region us-central1 \
        --format 'value(status.url)')
      echo "Cloud Run service URL: $SERVICE_URL"
