# build.yaml
# Build and deploy Python Cloud Run app

# Use built-in substitutions like $PROJECT_ID, $BUILD_ID
# Custom substitutions can be added if needed

steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/my-cloudrun-app:$BUILD_ID',
        '.'
      ]

  # Step 2: Push Docker image to Artifact Registry / Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'gcr.io/$PROJECT_ID/my-cloudrun-app:$BUILD_ID'
      ]

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Set GCP project (optional, usually already set in build environment)
        gcloud config set project $PROJECT_ID

        # Deploy to Cloud Run
        gcloud run deploy my-cloudrun-app \
          --image gcr.io/$PROJECT_ID/my-cloudrun-app:$BUILD_ID \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated

# Optional: define timeouts, artifacts, or substitutions
timeout: '1200s'  # 20 minutes

# Substitutions (optional)
substitutions:
  _CUSTOM_VAR: "example"

# Optionally, specify images to keep in Cloud Build artifacts
images:
  - 'gcr.io/$PROJECT_ID/my-cloudrun-app:$BUILD_ID'
