# cloudbuild-build.yaml
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"

substitutions:
  _PROJECT_ID: $PROJECT_ID
  _IMAGE_NAME: "my-cloudrun-app"

steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:$COMMIT_SHA', '.']

  # Step 2: Push Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:$COMMIT_SHA']

images:
  - 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:$COMMIT_SHA'
